context:
  version: 0.8.15

package:
  name: perlnavigator-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/perlnavigator-server/-/perlnavigator-server-${{ version }}.tgz
  sha256: 891d414a686ed2b44014ab17ea50d3e54d0b30a235e0b03b292e4c779ab64c74

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - perlnavigator --help 2>&1 | grep -q "Connection input stream is not set"

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Perl Language Server that includes syntax checking, perl critic, and code navigation
  homepage: https://github.com/bscan/PerlNavigator
  repository: https://github.com/bscan/PerlNavigator

extra:
  recipe-maintainers:
    - danielnachun
