context:
  version: "0.8.19"

package:
  name: perlnavigator-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/perlnavigator-server/-/perlnavigator-server-${{ version }}.tgz
  sha256: 7150c79093815fd2aecab971217c980f5ebc4af05b8d31c5e2f61433b6b68acc

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - perlnavigator --help 2>&1 | grep -q "Connection input stream is not set"

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Perl Language Server that includes syntax checking, perl critic, and code navigation
  homepage: https://github.com/bscan/PerlNavigator
  repository: https://github.com/bscan/PerlNavigator

extra:
  recipe-maintainers:
    - danielnachun
